gridWorkingDir:         workingdir
gridOutputDir:          outputdir_13b2_efix_p1_1run_chargedTruthJets
aliROOTVersion:         v5-09-34-1
aliPhysicsVersion:      vAN-20180727-1
#package:                fastjet::v3.2.1_1.024-alice3-2
#package:                cgal::v4.6.3-25
#package:                boost::v1.59.0-19
#package:                MPFR::v3.1.3-4
#package:                GMP::v6.0.0-2
#package:                GCC-Toolchain::v4.9.3-alice3-1
gridDataDir:            /alice/sim/2013/LHC13b2_efix_p1/
dataPattern:            */*/AliESDs.root
#runNumber:              [195673,195677,195675,195644, 195483,195568]
runNumber:              [195592]
runPrefix:
emcalCorrection:	emcal_correctionMC.yaml
emcalGeometryFilename:	geometry_2015.root
emcalLocal2MasterFilename: EMCALlocal2master.root
splitMaxInputFileNumber:        20.0