gridWorkingDir:			workingdir
gridOutputDir:			outputdir_13d_test_TriggerMinBias_4GeVTrack
aliROOTVersion:			v5-09-23-1
aliPhysicsVersion:		vAN-20180222-1
gridDataDir:			/alice/data/2013/LHC13d
dataPattern:			/pass4/*/AliESDs.root
runPrefix:              	000
runNumber:			[195872]
emcalCorrection:		emcal_correction.yaml
emcalGeometryFilename:  	geometry_2015.root
emcalLocal2MasterFilename:  	EMCALlocal2master.root
skimTrigger:			MinBias
splitMaxInputFileNumber: 	10.0
