gridWorkingDir:         workingdir
gridOutputDir:          outputdir_18b10a_calo_pthat4_v1_wCrossTalk
aliROOTVersion:         v5-09-27-1
aliPhysicsVersion:      vAN-20180423-1
gridDataDir:            /alice/sim/2018/LHC18b10a_calo/4/
dataPattern:            */*/AliESDs.root
runPrefix:
runNumber:              [282439, 282402, 282441, 282437, 282415, 282399, 282391]
emcalCorrection:        emcal_correction.yaml
emcalGeometryFilename:          geometry_2015.root
emcalLocal2MasterFilename:      EMCALlocal2master.root