gridWorkingDir:         workingdir
gridOutputDir:          outputdir_18b10a_calo_pthat2_v1_1run
aliROOTVersion:         v5-09-27-1
aliPhysicsVersion:      vAN-20180423-1
gridDataDir:            /alice/sim/2018/LHC18b10a_calo/2/
dataPattern:            */*/AliESDs.root
runPrefix:
runNumber:              [282439]
emcalCorrection:        emcal_correction.yaml