gridWorkingDir:         workingdir
gridOutputDir:          outputdir_18g7a_calo_pthat1_4runs
aliROOTVersion:         v5-09-34-1
aliPhysicsVersion:      vAN-20180727-1
#package:                fastjet::v3.2.1_1.024-alice3-2
#package:                cgal::v4.6.3-25
#package:                boost::v1.59.0-19
#package:                MPFR::v3.1.3-4
#package:                GMP::v6.0.0-2
#package:                GCC-Toolchain::v4.9.3-alice3-1
gridDataDir:            /alice/sim/2018/LHC18g7a_calo/1
dataPattern:            */*/AliESDs.root
runPrefix:
runNumber:              [282441, 282440, 282439, 282437]
emcalCorrection:        emcal_correctionMC.yaml
splitMaxInputFileNumber:        20.0